### ISSUE TITLE
Remove theme from URL and use users preferences

### ISSUE THREAD

**Issue by dennisreimann** [btcpayserver/btcpayserver.org#104]
Similar to [what we did in the directory](https://github.com/btcpayserver/directory.btcpayserver.org/commit/15928d9c3bf50b870981355071a92bd29a52d617):

* Remove the light/dark path segement from the URL 
* Move the preference to localStorage
* Initially use the users system preferences to look up the prefered theme

Relevant code snippets from the above commit:

```js
const COLOR_MODES = ["light", "dark"];
const systemColorMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
const userColorMode = window.localStorage.getItem('colorMode');
const colorMode = COLOR_MODES.includes(userColorMode) ? userColorMode : systemColorMode;

window.localStorage.setItem("colorMode", mode);
```

**Comment by Dorson** [comment]
Made exactly that for the night and evening time.

The @media screen and (prefers-color-scheme: dark) {}  CSS rule could work with Pure CSS alone. No need for the JavaScript to handle that, because it's being adopted more and more by the browsers today.

For the more complex cases: see live demo on my GitHub page:

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Have fun, feel free to fork, copy, adopt, port, etc...

**Comment by dennisreimann** [comment]
@Dorson correct, but we decided on having an explicit switch also.
