### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#18]
We should have the main site in different languages. There's not really much to translate. Leaving this here for future and brainstorming. 
I guess we should tackle it the same way we tackled other translations, via Transifex.
Tagging our experts @britttttk and @vswee for a brainstorm session.

**Comment by Karem-sobhy** [comment]
i'm in for Arabic Translation but make rtl support pls :D

**Comment by vswee** [comment]
@kemoantemo shoot me a message on mattermost (ed_flat18). I could use your help to make sure the rtl layout actually makes sense in your language. Demo site is getting RTL-ed.

**Comment by vswee** [comment]
Raw en-gb readout of website strings can be found at [here](https://experimental-btcpayserver.flat18.co.uk/resource/translation/en-gb.json) to help with translations.

**Comment by huey735** [comment]
@vswee do you have a link to the demo of the site with the translations or a description of the process to implement it?

**Comment by vswee** [comment]
@huey735 Demo site: https://btcpayserver.flat18.co.uk/
The JSON file at https://experimental-btcpayserver.flat18.co.uk/resource/translation/json/en.json
is generated from looping over the real elements on the demo site. ~~Every element is given a corresponding index to the string in the file and the translation script basically loops back over and replaces the strings from the translation files according to the same index. Today I'll be smartening up the translation script so that it changes only the text in links etc. instead of rewriting them as text.~~

**Comment by pavlenex** [comment]
DONEEEE ❤️
