### ISSUE TITLE
Please add build instructions.

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver.org#71]
Please document how to build or add a bash script that builds or something. I want to eventually automate builds via Github Actions while also testing my changes locally

**Comment by NicolasDorier** [comment]
@Kukks  github.io is for static pages, there is no build.

**Comment by Kukks** [comment]
There is, Ed just does it manually each time offline from the `source` folder to the root dir. The main issue is we don't have access to the tooling or how he does it

**Comment by Kukks** [comment]
`Current build process requires a manual build command when a resource is updated.`
```
How to build

More details on this workflow and how to build the site locally to come.
```

**Comment by vswee** [comment]
> The main issue is we don't have access to the tooling or how he does it

I'll work on making it presentable and see about adding it to the source. 

It currently builds in PHP by pulling down all the transifex files, looping over them and doing a string replace on the index template. It minifies and inserts the css and js files into the template in the loop too. I expect you've got a less bloated way of building @Kukks :)

**Comment by dennisreimann** [comment]
Let‘s try to automate it using GH Actions like I did with [this script](https://github.com/dennisreimann/btcpayserver-ui-prototype/blob/master/.github/workflows/nodejs.yml).

**Comment by vswee** [comment]
@dennisreimann This url:[https://btcpayserver.flat18.co.uk/source/translator.php?source=git]( https://btcpayserver.flat18.co.uk/source/translator.php?source=git) clones/pulls the repo, builds the site and saves it to the git (in ~50s) but doesn't push or commit yet. Could that work for actions from a security perspective?

**Comment by Kukks** [comment]
Can we have the source code for it? It should be in this repository.

**Comment by dennisreimann** [comment]
> Could that work for actions from a security perspective?

imho it'd be best to have it in the repo and make it part of an automatic build, so that only the CI process (GH Action) could trigger it.

**Comment by vswee** [comment]
@dennisreimann @Kukks want to help me do it 🤞? The scripts will just fill up the website repo with PRs and issues for it so probably prudent to have it in decent order to start. @ndeet was making headway some time back, shall we pick it back up again?

**Comment by dennisreimann** [comment]
Yeah, let‘s pull this off together :)

**Comment by ndeet** [comment]
Hi everybody! Yes I suggested the same thing a few months back, to have a reproducible build script/whatever here in the repo so that any contributor can fully build the site as there should be no manual intervention needed when PRs come in. 

@vswee thankfully changed and moved files to source directory to separate things and I tested a few iterations of a build script but there were some questions open as files got removed, so I was not able to reproducibly build the dist files and we lost the conversation at some point.

The next steps would be imo:

- @vswee please commit what you have and remove/replace credentials with environment variables which anybody can set on their own if needed
- some short instructions how it works/can be executed
- from here we can together understand what is needed and collaborate move the build to GH actions
- bonus: would be great that generated files end up in `dist/` directory and we can map gh-pages to use that as docroot and not have generated files in the root directory (not sure if that is possible)

**Comment by dennisreimann** [comment]
Great plan, @ndeet! 👍

> bonus: would be great that generated files end up in dist/ directory and we can map gh-pages to use that as docroot and not have generated files in the root directory (not sure if that is possible)

The way that most other scripts do it is creating a build, initializing a new repo in the dist directory and force pushing the result to the `gh-pages` branch. (see [this example](https://github.com/maxheld83/ghpages/blob/master/entrypoint.sh))

**Comment by ndeet** [comment]
@dennisreimann interesting, thank you. 

Looking into gh-pages we have some options here it seems. On settings you can select any branch or you can select master `/docs` directory also https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

So we have following options: 
- the script you mentioned to push dist only into root dir of a branch e.g. `gh-pages` and define that in gh-pages settings
- we use master branch /docs suggestion (so generated files will end up there)

I have no hard feelings about those options. While putting generated files (I normally would put into /dist) into /docs is not what I used to do it sounds like a easy solution without any additional script. 
On the other hand having an automatically build dedicated branch is also a clean separation which makes sense imo.

**Comment by vswee** [comment]
There are comments throughout the file but will likely need more clarification on things so just shoot any questions over

**Comment by dennisreimann** [comment]
Alright, thanks! I'll take a look :)

**Comment by dennisreimann** [comment]
I started to break the build apart into smaller steps on the [automate-build branch](https://github.com/dennisreimann/btcpayserver.github.io/commits/automate-build) of my fork.

I'd try to move this to npm scripts as the JS ecosystem should offer the best tooling for this kind of build and creating a static website. Right now only the tasks for copying of the static files and downloading the translations from Transifex exist, but I'll work on this more to tackle these TODOS I see:

- [ ] Building HTML files based on the translations
- [x] Building video subtitle files based on the translations
- [ ] Optimization steps: Minify HTML and static assets (images, css, js)
- [ ] Add GitHub Actions to automatically build and deploy the site

The first task seems to be the most complicated and I haven't understood this fully yet. It'd be great to also split this part up and make it more maintainable as it contains lots of variables. Nevertheless I think we can make this work in a straight-forward manner and automate the build rather sooner than later.

Note: Once we are done we should also create a new token for Transifex as having it visible to everyone in the repo might not be ideal.

Feedback and help welcome! See this as a conversation starter and I have started to lay out my ideas so that we can discuss the direction this should take.

**Comment by vswee** [comment]
Building the HTML files is actually the most straightforward bit.

- get array of available transifex languages with ~>90% completed translations
- loop over that array and perform string replace the markers in the template files
- unlink/empty and (re)make locale folders [e.g. "ru", "uk"] as part of loop
- repeat process for donation page and sub-directory (in future-proofing against multiple webpages per sub-directory this method may need upgrading to a more widely applicable class)

whole css and js files are inserted into the template too but could be linked if it's simpler.
some translation strings are broken down in script to accommodate for sentences which include inline urls with css. This look messy but could be simplified slightly if perhaps the master en.json file was modified.

**Comment by dennisreimann** [comment]
I tried to start with the video vtt files, but there seems to be [some kind of magic](https://github.com/btcpayserver/btcpayserver.github.io/blob/master/source/translator.php#L656) going on and I don't really get how it works: Can you elaborate on why and how the translation parts are split up for the loop?

Regarding the assets: IMHO we should just have them as separate files, so that they are not inlined in each HTML file. This way the HTML files are smaller and the CSS and JS can be cached across the different translations.

**Comment by dennisreimann** [comment]
> Can you elaborate on why and how the translation parts are split up for the loop?

Got it, so the video files are also created on the branch now :)

**Comment by Kukks** [comment]
> 
> 
> I started to break the build apart into smaller steps on the [automate-build branch](https://github.com/dennisreimann/btcpayserver.github.io/commits/automate-build) of my fork.
> 
> I'd try to move this to npm scripts as the JS ecosystem should offer the best tooling for this kind of build and creating a static website. Right now only the tasks for copying of the static files and downloading the translations from Transifex exist, but I'll work on this more to tackle these TODOS I see:
> 
>     * [ ]  Building HTML files based on the translations
> 
>     * [x]  Building video subtitle files based on the translations
> 
>     * [ ]  Optimization steps: Minify HTML and static assets (images, css, js)
> 
>     * [ ]  Add GitHub Actions to automatically build and deploy the site
> 
> 
> The first task seems to be the most complicated and I haven't understood this fully yet. It'd be great to also split this part up and make it more maintainable as it contains lots of variables. Nevertheless I think we can make this work in a straight-forward manner and automate the build rather sooner than later.
> 
> Note: Once we are done we should also create a new token for Transifex as having it visible to everyone in the repo might not be ideal.
> 
> Feedback and help welcome! See this as a conversation starter and I have started to lay out my ideas so that we can discuss the direction this should take.

Make a draft PR to here so we can follow this better :)

**Comment by dennisreimann** [comment]
I‘ll do once the website rendering is done. As my previous comment made clear we‘ll need to polish this together. There are some details I don‘t know about and I am looking forward to @vswee‘s feedback. 😀

**Comment by dennisreimann** [comment]
Alright, let's discuss this further in #75 as we are almost done with the basics.

**Comment by dennisreimann** [comment]
Done, see  #75.
